spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mohan-Sharma/centralized-configuration.git
          username: Mohan-Sharma
          password:
server:
  port: 8888